"""更新表

Revision ID: 9321e378ec2b
Revises: 85a4a38712bc
Create Date: 2018-12-06 09:29:34.194970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9321e378ec2b'
down_revision = '85a4a38712bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_timestamp'), 'project', ['timestamp'], unique=False)
    op.drop_index('ix_projects_timestamp', table_name='project')
    op.create_index(op.f('ix_resource_timestamp'), 'resource', ['timestamp'], unique=False)
    op.drop_index('ix_resources_timestamp', table_name='resource')
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.drop_index('ix_roles_default', table_name='role')
    op.drop_constraint('role_permission_ibfk_1', 'role_permission', type_='foreignkey')
    op.drop_constraint('role_permission_ibfk_2', 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'])
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_users_email', table_name='user')
    op.drop_index('ix_users_username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'user', ['username'], unique=True)
    op.create_index('ix_users_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key('role_permission_ibfk_2', 'role_permission', 'permission', ['permission_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('role_permission_ibfk_1', 'role_permission', 'role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_roles_default', 'role', ['default'], unique=False)
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.create_index('ix_resources_timestamp', 'resource', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_resource_timestamp'), table_name='resource')
    op.create_index('ix_projects_timestamp', 'project', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_project_timestamp'), table_name='project')
    # ### end Alembic commands ###
