"""更新表

Revision ID: 94181a1a84c3
Revises: 9321e378ec2b
Create Date: 2018-12-11 09:26:57.892367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94181a1a84c3'
down_revision = '9321e378ec2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_resource', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.alter_column('project_resource', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('project_resource', 'resource_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('project_resource', 'timestamp')
    op.alter_column('role_permission', 'permission_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('role_permission', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permission', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('role_permission', 'permission_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('project_resource', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.alter_column('project_resource', 'resource_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('project_resource', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('project_resource', 'create_time')
    # ### end Alembic commands ###
