"""为permission表添加pclass字段

Revision ID: a96b1c22314a
Revises: d3a6a8ca214c
Create Date: 2018-12-29 09:31:49.556987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a96b1c22314a'
down_revision = 'd3a6a8ca214c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('pclass', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'pclass')
    # ### end Alembic commands ###
